x-airflow-common:
  user: "${AIRFLOW_UID}:0"


services:
  weather-postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
      POSTGRES_DB: weather

    volumes:
      - weather_pg_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d:ro

    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U weather -d weather"]
      interval: 10s
      timeout: 5s
      retries: 5
      

  airflow-postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_pg_data:/var/lib/postgresql/data

  
  airflow-init:
    image: apache/airflow:2.10.1
    
    depends_on:
      - airflow-postgres
    
    environment:
      AIRFLOW__CORE__EXECUTOR: airflow.executors.local_executor.LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_WEATHER_DB: postgresql+psycopg2://weather:weather@weather-postgres:5432/weather
    
    entrypoint: /bin/bash
    
    command:
      - -c
      - |
        airflow db init
        airflow users create \
          --username airflow \
          --password airflow \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com


  airflow-scheduler:
    image: apache/airflow:2.10.1

    depends_on:
      - airflow-postgres
      - weather-postgres
      - airflow-init

    environment:
      AIRFLOW__CORE__EXECUTOR: airflow.executors.local_executor.LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_WEATHER_DB: postgresql+psycopg2://weather:weather@weather-postgres:5432/weather
      _PIP_ADDITIONAL_REQUIREMENTS: requests
    
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

    command: scheduler
  
  airflow-webserver:
    image: apache/airflow:2.10.1

    depends_on:
      - airflow-scheduler
      - airflow-init

    environment:
      AIRFLOW__CORE__EXECUTOR: airflow.executors.local_executor.LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_WEATHER_DB: postgresql+psycopg2://weather:weather@weather-postgres:5432/weather
      _PIP_ADDITIONAL_REQUIREMENTS: requests

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    

    ports:
      - "8080:8080"

    command: webserver
  

volumes:
  weather_pg_data:
  airflow_pg_data: